language: php
php:
  - '7.0'

matrix:
  fast_finish: true

services:
  - mysql

env:
  - SYMFONY_VERSION="3.1.*" DB=mysql

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - mkdir -p build/logs

install:
  - mysql -e 'create database `kame`;'
  - composer install

script:
  - phpunit -c phpunit.xml.dist

cache:
  bundler: true
  directories:
  - vendor

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis_retry php vendor/bin/coveralls -v
