language: php
php:
  - '7.0'

matrix:
  fast_finish: true

services:
  - mongodb

env:
  - SYMFONY_VERSION="3.1.*" DB=mongodb

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - mkdir -p build/logs

before_install:
  - phpenv config-add travis/mongodb.ini

install:
  - composer install

script:
  - phpunit -c phpunit.xml.dist

cache:
  bundler: true
  directories:
  - vendor

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis_retry php vendor/bin/coveralls -v

after_script:
  - cat var/logs/test.log
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover -n build/logs/clover.xml
